# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
final_space: true
version: 2
transient_prompt:
  foreground_templates:
    - "{{if gt .Code 0}}red{{end}}"
    - "{{if eq .Code 0}}magenta{{end}}"
  background: 'transparent'
  template: '❯ '
secondary_prompt:
  foreground: 'magenta'
  background: 'transparent'
  template: '❯❯ '
blocks:
  - type: rprompt
    alignment: right
    overflow: hidden
    segments:
      - type: executiontime
        style: plain
        foreground: 'green'
        background: 'transparent'
        properties:
          threshold: 1000
      # - type: docker
      #   style: plain
      #   foreground: "green"
      #   background: "transparent"
      #   template: "  {{ .Context }} "
      # - type: kubectl
      #   style: plain
      #   foreground: 'green'
      #   background: 'transparent'
      #   template: " {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}} "
      - type: npm
        style: plain
        foreground: 'green'
        background: 'transparent'
        template: " {{ .Full }} "
      - type: deno
        style: plain
        foreground: 'green'
        background: 'transparent'
        template: "  {{ .Full }} "
      - type: bun
        style: plain
        foreground: 'green'
        background: 'transparent'
        template: " 🥟 {{ .Full }} "
      - type: terraform
        style: plain
        foreground: 'green'
        background: 'transparent'
        template: " {{ .WorkspaceName }}{{ if .Version }} {{ .Version }}{{ end }}"

  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: path
        style: plain
        foreground: "blue"
        background: "transparent"
        template: '{{ .Path }}'
        properties:
          style: full
      - type: git
        style: plain
        foreground: "green"
        background: "transparent"
        template: ' {{ .UpstreamIcon }} {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}<cyan>{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}</>'
        properties:
          fetch_status: true
          fetch_stash_count: true
          fetch_worktree_count: true
          fetch_upstream_icon: true
          fetch_bare_info: true
          branch_icon:  
          branch_identical_icon: ≡
          branch_ahead_icon: ↑
          branch_behind_icon: ↓
          branch_gone_icon: ≢
          commit_icon: 
          tag_icon: 
          rebase_icon: 
          cherry_pick_icon: 
          revert_icon: 
          merge_icon: 
          no_commits_icon: 
          github_icon: 
          gitlab_icon: 
          bitbucket_icon: 
          azure_devops_icon: 
          codecommit_icon: 
          codeberg_icon: 
          git_icon: 
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: text
        style: plain
        foreground_templates: [
          "{{if gt .Code 0}}red{{end}}",
          "{{if eq .Code 0}}magenta{{end}}",
        ]
        background: 'transparent'
        template: '❯'
